name: Kotlin Android CI Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK for Android
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # Step 4: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      # Step 5: Grant executable permissions to the gradlew script
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      # Step 5: Build the project
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Step 6: Run Lint checks
      - name: Run Kotlin Lint
        run: ./gradlew lintDebug


      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest